spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/features
        username: diogo
        password: diogo
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
server:
    error:
        include-message: always
app:
    security:
        jwt:
            secret: SECRET
            expiration-time-ms: 300000